"""Initial DevFeed schema.

Revision ID: 0001_initial
Revises:
App version: 0.0.1

Fresh databases only. This replaces the pre-release migration history.
Future schema changes must be added as new revision files.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None
app_version: str = "0.0.1"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("ai_description", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "publication_status", sa.String(length=20), server_default="unpublished", nullable=False
        ),
        sa.Column("published_to_feed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("editorial_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "classification_provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("content_type", sa.String(length=30), nullable=False),
        sa.Column("content_format", sa.String(length=30), server_default="article", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("feed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_source_type", sa.String(length=20), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "metadata_source_type IN ('publisher', 'aggregator', 'page')",
            name="ck_articles_metadata_source_type",
        ),
        sa.CheckConstraint(
            "publication_status <> 'published' OR review_status = 'approved'",
            name="ck_article_published_approved",
        ),
        sa.CheckConstraint(
            "publication_status IN ('unpublished','published')", name="ck_article_publication"
        ),
        sa.CheckConstraint(
            "review_status IN ('pending','approved','rejected')", name="ck_article_review"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_hash"),
    )
    op.create_index(
        "ix_articles_feed",
        "articles",
        [sa.literal_column("feed_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_articles_search",
        "articles",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((title::text || ' '::text) || summary) "
                "|| ' '::text) || COALESCE(ai_summary, ''::text))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("feed_url", sa.String(length=2048), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("website_url", sa.String(length=2048), nullable=True),
        sa.Column("logo_url", sa.String(length=2048), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("submitted_by", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("submission_channel", sa.String(length=20), nullable=False),
        sa.Column("approval_status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("review_note", sa.String(length=1000), nullable=True),
        sa.Column("metadata_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_error", sa.String(length=1000), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("etag", sa.String(length=1000), nullable=True),
        sa.Column("last_modified", sa.String(length=1000), nullable=True),
        sa.Column("next_fetch_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "approval_status IN ('pending','approved','rejected')",
            name="ck_sources_approval_status",
        ),
        sa.CheckConstraint(
            "source_type IN ('publisher', 'aggregator')", name="ck_sources_source_type"
        ),
        sa.CheckConstraint(
            "submission_channel IN ('api','cli','legacy')", name="ck_sources_submission_channel"
        ),
        sa.CheckConstraint("poll_interval_seconds >= 300"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_url"),
    )
    op.create_index(
        op.f("ix_sources_approval_status"), "sources", ["approval_status"], unique=False
    )
    op.create_index(
        "ix_sources_due",
        "sources",
        ["next_fetch_at"],
        unique=False,
        postgresql_where=sa.text("enabled IS true AND approval_status = 'approved'"),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ai_description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=2048), nullable=True),
        sa.Column("logo_url", sa.String(length=2048), nullable=True),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('proposed','active','rejected')", name="ck_topic_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "article_analysis_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("catalog_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("editorial_revision", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed')", name="ck_analysis_status"
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_article_analysis_dispatch",
        "article_analysis_jobs",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        op.f("ix_article_analysis_jobs_article_id"),
        "article_analysis_jobs",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        "uq_article_analysis_active",
        "article_analysis_jobs",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "article_contents",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_table(
        "article_enrichment_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.Column("changed_fields", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('enriched','metadata_only','not_found','superseded','unapproved')"
        ),
        sa.CheckConstraint("status IN ('queued','running','succeeded','failed')"),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_article_enrichment_dispatch",
        "article_enrichment_jobs",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        op.f("ix_article_enrichment_jobs_article_id"),
        "article_enrichment_jobs",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        "uq_article_enrichment_active",
        "article_enrichment_jobs",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "article_image_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("method", sa.String(length=30), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint("outcome IN ('found','not_found','already_present')"),
        sa.CheckConstraint("status IN ('queued','running','succeeded','failed')"),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_article_image_dispatch",
        "article_image_jobs",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        op.f("ix_article_image_jobs_article_id"), "article_image_jobs", ["article_id"], unique=False
    )
    op.create_index(
        "uq_article_image_active",
        "article_image_jobs",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "article_origins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("entry_key", sa.String(length=64), nullable=False),
        sa.Column("original_url", sa.String(length=2048), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "entry_key"),
    )
    op.create_index(
        op.f("ix_article_origins_article_id"), "article_origins", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_article_origins_source_id"), "article_origins", ["source_id"], unique=False
    )
    op.create_table(
        "article_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_article_reviews_article_id"), "article_reviews", ["article_id"], unique=False
    )
    op.create_table(
        "article_topics",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "role IN ('primary','supporting','comparison','incidental')",
            name="ck_article_topic_role",
        ),
        sa.CheckConstraint("relevance >= 0 AND relevance <= 1", name="ck_article_topic_relevance"),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "topic_id"),
    )
    op.create_index(
        "ix_article_topics_topic", "article_topics", ["topic_id", "article_id"], unique=False
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("parent_id <> id", name="ck_categories_not_self_parent"),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("entries_seen", sa.Integer(), nullable=False),
        sa.Column("articles_created", sa.Integer(), nullable=False),
        sa.Column("entries_skipped", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint("status IN ('queued','running','succeeded','failed')"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_dispatch",
        "ingestion_jobs",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_source_id"), "ingestion_jobs", ["source_id"], unique=False
    )
    op.create_index(
        "uq_ingestion_active_source",
        "ingestion_jobs",
        ["source_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "source_enrichment_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column("changed_fields", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.CheckConstraint("status IN ('queued','running','succeeded','failed')"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_source_enrichment_dispatch",
        "source_enrichment_jobs",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        op.f("ix_source_enrichment_jobs_source_id"),
        "source_enrichment_jobs",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        "uq_source_enrichment_active",
        "source_enrichment_jobs",
        ["source_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table(
        "source_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("decision IN ('approved','rejected')"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_reviews_source_id"), "source_reviews", ["source_id"], unique=False
    )
    op.create_table(
        "topic_relations",
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("related_topic_id", sa.Uuid(), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("evidence_url", sa.String(length=2048), nullable=True),
        sa.CheckConstraint("topic_id <> related_topic_id", name="ck_topic_relation_not_self"),
        sa.ForeignKeyConstraint(["related_topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "related_topic_id", "relation"),
    )
    op.create_table(
        "article_categories",
        sa.Column("origin", sa.String(length=20), server_default="heuristic", nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "category_id"),
    )
    op.create_index(
        "ix_article_categories_category",
        "article_categories",
        ["category_id", "article_id"],
        unique=False,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_tags_category_id"), "tags", ["category_id"], unique=False)
    op.create_table(
        "article_tags",
        sa.Column("origin", sa.String(length=20), server_default="heuristic", nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "tag_id"),
    )
    op.create_index("ix_article_tags_tag", "article_tags", ["tag_id", "article_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_article_tags_tag", table_name="article_tags")
    op.drop_table("article_tags")
    op.drop_index(op.f("ix_tags_category_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index("ix_article_categories_category", table_name="article_categories")
    op.drop_table("article_categories")
    op.drop_table("topic_relations")
    op.drop_index(op.f("ix_source_reviews_source_id"), table_name="source_reviews")
    op.drop_table("source_reviews")
    op.drop_index(
        "uq_source_enrichment_active",
        table_name="source_enrichment_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_source_enrichment_jobs_source_id"), table_name="source_enrichment_jobs")
    op.drop_index(
        "ix_source_enrichment_dispatch",
        table_name="source_enrichment_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("source_enrichment_jobs")
    op.drop_index(
        "uq_ingestion_active_source",
        table_name="ingestion_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_ingestion_jobs_source_id"), table_name="ingestion_jobs")
    op.drop_index(
        "ix_ingestion_dispatch",
        table_name="ingestion_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index("ix_article_topics_topic", table_name="article_topics")
    op.drop_table("article_topics")
    op.drop_index(op.f("ix_article_reviews_article_id"), table_name="article_reviews")
    op.drop_table("article_reviews")
    op.drop_index(op.f("ix_article_origins_source_id"), table_name="article_origins")
    op.drop_index(op.f("ix_article_origins_article_id"), table_name="article_origins")
    op.drop_table("article_origins")
    op.drop_index(
        "uq_article_image_active",
        table_name="article_image_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_article_image_jobs_article_id"), table_name="article_image_jobs")
    op.drop_index(
        "ix_article_image_dispatch",
        table_name="article_image_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("article_image_jobs")
    op.drop_index(
        "uq_article_enrichment_active",
        table_name="article_enrichment_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        op.f("ix_article_enrichment_jobs_article_id"), table_name="article_enrichment_jobs"
    )
    op.drop_index(
        "ix_article_enrichment_dispatch",
        table_name="article_enrichment_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("article_enrichment_jobs")
    op.drop_table("article_contents")
    op.drop_index(
        "uq_article_analysis_active",
        table_name="article_analysis_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_article_analysis_jobs_article_id"), table_name="article_analysis_jobs")
    op.drop_index(
        "ix_article_analysis_dispatch",
        table_name="article_analysis_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("article_analysis_jobs")
    op.drop_table("topics")
    op.drop_index(
        "ix_sources_due",
        table_name="sources",
        postgresql_where=sa.text("enabled IS true AND approval_status = 'approved'"),
    )
    op.drop_index(op.f("ix_sources_approval_status"), table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_articles_search", table_name="articles", postgresql_using="gin")
    op.drop_index("ix_articles_feed", table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
