import assert from "node:assert/strict";

export function withManagedImage(article) {
  article.image_url = "https://images.example.test/thumbnails/v1/fixture/960.webp";
  article.image_variants = [320, 640, 960].map((width) => ({
    url: `https://images.example.test/thumbnails/v1/fixture/${width}.webp`,
    width,
  }));
}

export async function mockManagedImages(context) {
  await context.route("https://images.example.test/**", (route) =>
    route.fulfill({
      contentType: "image/png",
      body: Buffer.from(
        "iVBORw0KGgoAAAANSUhEUgAAA8AAAAGQCAIAAADupZ4SAAAHvklEQVR4nO3WwQ3AIBDAsNLpb2xWIC+EZE+QZ9bMfAAAwJn/dgAAALzEQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAIIN4owEuC0eTrQAAAAASUVORK5CYII=",
        "base64",
      ),
    }),
  );
}

export async function checkManagedImages(page) {
  const image = page.locator(".article-card .card-image img").first();
  await image.waitFor();
  await page.waitForFunction(() => {
    const image = document.querySelector(".article-card .card-image img");
    return image?.complete && image.naturalWidth > 0;
  });
  assert.match(
    await image.getAttribute("srcset"),
    /320\.webp 320w,.*640\.webp 640w,.*960\.webp 960w/,
  );
  assert.match(
    await image.evaluate((element) => element.currentSrc),
    /^https:\/\/images\.example\.test\//,
  );
}
