name: Containers
on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        default: false
permissions:
  contents: read
jobs:
  images:
    uses: abhi1693/actions/.github/workflows/container-images.yml@59178a1adfb1547da9ba94fdd46962c510b8eb1f
    with:
      manifest: .github/images.json
      publish: ${{ inputs.publish }}
      version-file: pyproject.toml
      latest: false
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
